- name: Tag Play 1
  hosts: all
  tags:
      - Tag Play 1
  tasks:
    - debug:
        msg: "TAG  Play 1 PLAY"
- name: CONFIG
  hosts: all
  tags:
    - config
  tasks:
    - debug:
        msg: "CONFIG PLAY"

## Tags are 